### ISSUE TITLE
npm run build-themes Unable to parse dart server response

### ISSUE THREAD

**Issue by anissouissi** [DevExpress/devextreme-angular-template#149]
Hello,
I'm trying to install the template by running 
`npx -p devextreme-cli devextreme new angular-app app-name`

Everything went fine until it come to step `npm run build-themes`

I get this error:
```
line: null Unable to parse dart server response
at CompileManager.<anonymous> (C:\dev\app-name\node_modules\devextreme-cli\node_modules\devextreme-themebuilder\modules\compile-manager.js:67:23)
    at Generator.throw (<anonymous>)
    at rejected (C:\dev\app-name\node_modules\devextreme-cli\node_modules\devextreme-themebuilder\modules\compile-manager.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I'm running these commands behind company proxy.
I don't know if it could affect the installation.

I setup the proxy config in npm and I can install all packages

Could you please help me ?

Thank you

**Comment by bertvan** [comment]
Did you manage to find the solution?

**Comment by babich-a** [comment]
Hi,
The `build-themes` command can use the supporting server and try to find it in `127.0.0.1:22000`. Please check that this port is not used by some other application.

**Comment by bertvan** [comment]
That's it, thanks.
